/*
    Generated by Atomist on 30 06 2016 
*/
package com.jacky;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class X13Application {

    public static void main(String[] args) {
        SpringApplication.run(X13Application.class, args);
    }
}
