/*
    Generated by Atomist on 30 06 2016 
*/
package com.jacky;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.web.WebAppConfiguration;
import org.springframework.boot.test.SpringApplicationConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = X13Application.class)
@WebAppConfiguration
public class X13ApplicationTests {

	@Test
	public void contextLoads() {
	}
}
